version: "3.9"
services:

    webgoat:
        container_name: "webgoat"
        image: santosomar/webgoat
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.11
                
    juice-shop:
        container_name: "juice-shop"
        image: santosomar/juice-shop
        restart: unless-stopped
        environment:
          NODE_ENV: ctf
          CTF_KEY: XwCkRJnHedckasA3yJb3scMP2Qc2T
        networks:
            websploit:
                ipv4_address: 10.6.6.12
                
    dvwa:
        container_name: "dvwa"
        image: santosomar/dvwa
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.13


    mutillidae_2:
        container_name: "mutillidae_2"
        image: santosomar/mutillidae_2
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.14

    dvna:
        container_name: "dvna"
        image: santosomar/dvna
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.15

    hackazon:
        container_name: "hackazon"
        image: santosomar/hackazon
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.16

    hackme-rtov:
        container_name: "hackme-rtov"
        image: santosomar/hackme-rtov
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.17

    mayhem:
        container_name: "mayhem"
        image: santosomar/mayhem
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.18

    rtv-safemode:
        container_name: "rtv-safemode"
        image: santosomar/rtv-safemode
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.19

    grayhat-mmxx:
        container_name: "grayhat-mmxx"
        image: santosomar/grayhat-mmxx
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.20

    yascon-hackme:
        container_name: "yascon-hackme"
        image: santosomar/yascon-hackme
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.21

   
    secretcorp-branch1:
        container_name: "secretcorp-branch1"
        image: santosomar/secretcorp-branch1
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.22
    
    
    gravemind:
        container_name: "gravemind"
        image: santosomar/gravemind
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.23

    dc30_01:
      container_name: "dc30_01"
      image: santosomar/dc30_01:latest
      restart: unless-stopped
      networks:
            websploit:
                ipv4_address: 10.6.6.24

    dc30_02:
      container_name: "dc30_02"
      image: santosomar/dc30_02:latest
      restart: unless-stopped
      networks:
            websploit:
                ipv4_address: 10.6.6.25


networks:
    websploit:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.6.0/24
                  gateway: 10.6.6.1
